test_3/article/urls.py
from django.conf.urls import url

from . import views

app_name = "article"

urlpatterns = [
    url(r'^index/$', views.index, name="index"),
    url(r'^register/$', views.register, name="register"),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^psw_update/$', views.psw_update, name="psw_update"),
    url(r'^upload_avatar/$', views.upload_avatar, name="upload_avatar"),

    url(r'^user_list/$', views.user_list, name="user_list"),
    url(r'^user_update/$', views.user_update, name="user_update"),
    url(r'^user_info/$', views.user_info, name="user_info"),
    url(r'^(?P<user_id>\d+)/user_delete/$', views.user_delete, name="user_delete"),

    url(r"^article_add/$", views.article_add, name="article_add"),
    url(r"^article_delete/(?P<a_id>\d+)/$", views.article_delete, name="article_delete"),
    url(r"^article_update/(?P<a_id>\d+)/$", views.article_update, name="article_update"),
    url(r"^article_detail/(?P<a_id>\d+)/$", views.article_detail, name="article_detail"),
    url(r"^article_list/$", views.article_list, name="article_list"),
    url(r"^code/$", views.code, name="code"),
]

test_3/test_3/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url('admin/', admin.site.urls),
    url("^article/",include("article.urls"))
]

test_3/article/models.py
from datetime import datetime

from django.db import models

from tinymce import models as t_models


class User(models.Model):
    """
        博客用户类
    """
    id = models.AutoField(primary_key=True, verbose_name="用户主键")
    username = models.CharField(max_length=100, unique=True, verbose_name="用户名称")
    password = models.CharField(max_length=255, verbose_name="用户密码")
    nickname = models.CharField(max_length=255, default="普通用户", verbose_name="用户昵称")
    age = models.IntegerField(default=18, verbose_name="用户年龄")
    gender = models.CharField(max_length=10, default="女", verbose_name="用户性别")
    email = models.CharField(max_length=255, null=True, blank=True, verbose_name="用户邮箱")
    avatar = models.ImageField(upload_to="static/img/", default="static/article/img/default.gif", verbose_name="用户头像")
    tel = models.CharField(max_length=50, default="110", verbose_name="用户头像")


class Article(models.Model):
    """ 文章类"""
    id = models.AutoField(primary_key=True, verbose_name="文章主键")
    title = models.CharField(max_length=100, verbose_name="文章标题")
    content = t_models.HTMLField(verbose_name="文章内容")
    remark = models.CharField(max_length=255, default="", verbose_name="文章摘要")
    publishTime = models.DateTimeField(auto_now_add=True, verbose_name="文章发表时间")
    modifyTime = models.DateTimeField(auto_now=True, verbose_name="文章修改时间")
    count = models.IntegerField(default=0, verbose_name="文章点击量")
    # 文章作者，也就是用户对象
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ["-publishTime"]

test_3/article/views.py
from io import BytesIO
import logging
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse,JsonResponse
import hmac,json
from django.core.paginator import Paginator
from django.core import serializers
from django.conf import settings
# from django.http import HttpResponseRedirect
# from django.core.urlresolvers import reverse

from . import models, utils, verify,cacheUtil


def index(request):
    logger = logging.getLogger("django")
    logger.info("首页开始加载数据量……")
    # add.delay()
    # 分页功能
    pageNow = int(request.GET.get("pageNow", 1))
    pageSize = settings.PAGE_SIZE
    articles = cacheUtil.getAllArticle()
    request.session.set_expiry(0)
    # 第一个参数是需要分页的数据列表，第二个参数是每页的数量
    paginator = Paginator(articles, pageSize)
    # page需要参数的当前页
    page = paginator.page(pageNow)
    return render(request, "article/index.html", {"page":page})


def register(request):
    """ 用户注册功能
    """
    if request.method == "GET":
        return render(request, "article/register.html", {"msg": "请认真填写如下选项"})
    elif request.method == "POST":
        username = request.POST["username"].strip()
        password = request.POST.get("password")
        confirmpwd = request.POST["confirmpwd"]
        nickname = request.POST["nickname"]
        email = request.POST["email"]
        tel = request.POST["tel"]
        age = int(request.POST["age"])
        gender = request.POST["gender"]
        try:
            avatar = request.FILES["avatar"]
        except:
            avatar = None
        verify_code = request.POST['verify_code'].strip()

        # 数据校验
        if username == "":
            return render(request, "article/register.html", {"msg": "用户名称不能为空"})
        if len(password) < 3:
            return render(request, "article/register.html", {"msg": "用户密码长度不能小于3位"})
        if password.strip() != confirmpwd.strip():
            return render(request, "article/register.html", {"msg": "两次密码不一致"})
        if nickname == "":
            return render(request, "article/register.html", {"msg": "用户昵称不能为空"})
        if age > 200:
            return render(request, "article/register.html", {"msg": "年龄不合理"})
        if gender != "男" and gender != "女":
            return render(request, "article/register.html", {"msg": "性别不合理"})
        if verify_code.upper() != request.session.get("code").upper():
            return render(request, "article/register.html", {"msg": "验证码错误"})

        # 用户名称不能重复
        try:
            models.User.objects.get(username=username)
            return render(request, "article/register.html", {"msg": "该用户名称已经存在，请重新输入"})
        except:
            try:
                password = utils.md5_by_hmac(password)
                # password = hmac.new(password.encode("utf-8"), "password".encode("uft-8"), "MD5")
                if avatar is None:
                    user = models.User(username=username, password=password, nickname=nickname, email=email, tel=tel,
                                       age=age, gender=gender)
                    user.save()
                else:
                    user = models.User(username=username, password=password, nickname=nickname, avatar=avatar,
                                       email=email, tel=tel, age=age, gender=gender)
                    user.save()
            except:
                return render(request, "article/register.html", {"msg": "注册失败，请重新注册"})

        return render(request, "article/login.html", {"msg": "用户注册成功！！，请登录"})


# @utils.create_code
def login(request):
    """ 用户登录功能
    """
    if request.method == "GET":
        return render(request, "article/login.html", {})
    else:
        # 接受页面的参数
        username = request.POST["username"].strip()
        password = request.POST["password"].strip()
        # verify_code = request.POST['verify_code'].strip()
        try:
            request.session.get("display")
            verify_code = request.POST['verify_code'].strip()
        except:
            verify_code = "no verify"
        password = utils.md5_by_hmac(password)
        # 数据校验
        if verify_code == "":
            return render(request, "article/login.html", {"msg": "验证码不能为空"})
        if username == "":
            return render(request, "article/login.html", {"msg": "用户名称不能为空"})
        if password == "":
            return render(request, "article/login.html", {"msg": "用户密码不能为空"})
        users = models.User.objects.filter(username=username)
        # print(verify_code.upper())
        if verify_code == "no verify" or verify_code.upper() == request.session.get("code").upper():
            if len(users) > 0:
                if users[0].password == password:
                    # 登录成功，需要保持用户的信息，以表示用户已经登录
                    request.session["loginUser"] = users[0]
                    request.session["tryTime"] = 0
                    try:
                        del request.session['display']
                    except:
                        pass
                    return redirect(reverse("article:user_list"))
                else:
                    try:
                        # request.session.get("tryTime")
                        request.session["tryTime"] += 1
                    except:
                        request.session["tryTime"] = 0
                    if request.session["tryTime"] > 2:
                        request.session["display"] = 1
                    nowTryTime=3-request.session["tryTime"]
                    if nowTryTime>0:
                        return render(request, "article/login.html", {"msg": "密码错误！！{tryTime}次后将输入验证码".format(tryTime=str(nowTryTime))})
                    else:
                        return render(request, "article/login.html", {"msg": "密码错误！！请输入验证码"})
            else:
                return render(request, "article/login.html", {"msg": "该用户名不存在！！"})
        else:
            return render(request, "article/login.html", {"msg": "验证码错误！！"})


@utils.requirelogin
def logout(request):
    """用户退出"""
    try:
        del request.session["loginUser"]
        return render(request, "article/login.html", {"msg": "用户退出成功，请重新登录！！"})
    except:
        return render(request, "article/login.html", {"msg": "用户退出成功，请重新登录！！"})


@utils.requirelogin
def user_list(request):
    users = models.User.objects.all()
    return render(request, "article/user_list.html", {"users": users})


@utils.requirelogin
def user_update(request):
    if request.method == "GET":
        id = request.GET["id"]
        user = models.User.objects.get(pk=id)
        return render(request, "article/user_update.html", {"users": user})
    else:
        nickname = request.POST["nickname"]
        age = request.POST["age"]
        gender = request.POST["gender"]
        email = request.POST["email"]
        tel = request.POST["tel"]

        user = models.User.objects.get(pk=request.session.get("loginUser").id)
        user.nickname = nickname
        user.age = age
        user.gender = gender
        user.email = email
        user.tel = tel

        user.save()
        request.session["loginUser"] = user
        return redirect(reverse("article:user_info"))


@utils.requirelogin
def user_delete(request):
    user = models.User.objects.get(pk=request.session.get("loginUser").id)
    user.delete()
    # return redirect("/article/user_list/")
    return redirect(reverse("article:user_list"))


def user_info(request):
    user = models.User.objects.get(id=request.session.get("loginUser").id)
    return render(request, "article/user_info.html", {"users": user})


@utils.requirelogin
def article_add(request):
    if request.method == "GET":
        return render(request, "article/article_add.html", {})
    elif request.method == "POST":
        title = request.POST["title"].strip()
        content = request.POST["content"].strip()
        # print(content)
        remark = utils.removeHTMLByRE(content)[:50]
        # print(content)
        author = request.session["loginUser"]

        # 验证
        if title == "":
            return render(request, "article/article_add.html", {"msg": "文字标题不能为空！"})
        if content == "":
            return render(request, "article/article_add.html", {"msg": "文字内容不能为空！"})

        at = models.Article(title=title, content=content, remark=remark, author=author)
        at.save()
        # 更新缓存
        cacheUtil.getAllArticle(ischange=True)
        return JsonResponse({"msg": "文章添加成功", "success": True})
        # return render(request,"article/index.html")

@utils.requirelogin
def article_delete(request, a_id):
    at = models.Article.objects.get(pk=a_id)
    at.delete()
    cacheUtil.getAllArticle(ischange=True)
    return redirect(reverse("article:article_list"))
    # return JsonResponse({"msg": "文章添加成功", "success": True})


@utils.requirelogin
def article_update(request, a_id):
    at = models.Article.objects.get(id=a_id)
    if request.method == "GET":
        return render(request, "article/article_update.html", {"article": at})
    else:
        title = request.POST["title"].strip()
        content = request.POST["content"].strip()
        remark = content[:50]
        # 验证
        if title == "":
            return render(request, "article/article_update.html", {"article": at, "msg": "文字标题不能为空！"})
        if content == "":
            return render(request, "article/article_update.html", {"article": at, "msg": "文字内容不能为空！"})

        at = models.Article.objects.get(pk=a_id)
        at.title = title
        at.content = content
        at.remark = remark
        at.save()
        return redirect(reverse("article:article_detail", kwargs={"a_id": at.id}))


def article_detail(request, a_id):
    at = models.Article.objects.get(pk=a_id)
    return render(request, "article/article_detail.html", {"article": at})


@utils.requirelogin
def article_list(request):
    ats = cacheUtil.getAllArticle()
    # articles=serializers.serialize("json",ats)
    # for i in ats:
    #     print(i.remark)

test_3/article/templates/article/article_add.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% block title%}发表文章{% endblock %}

{% block content%}
<div class="col-md-9">
    <div class="panel panel-primary">
        <div class="panel-heading">用户发表文章</div>
        <div class="panel-body">
            <h4 style="color: red">{{msg}}</h4>

            <form class="form-horizontal" action="{% url 'article:article_add'%}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">文章标题</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="title" id="title"
                               placeholder="请输入您的文章标题">
                    </div>
                </div>
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">文章内容</label>
                    <div class="col-md-9">
                        <textarea class="form-control" name="content" id="content" rows="20"
                                  placeholder="请输入您的文章内容"></textarea>
                        <script type="text/javascript" src="{% static 'article/js/tinymce/tiny_mce.js' %}"></script>
                        <script type="text/javascript">
                        tinyMCE.init({
                            mode: "textareas",
                            theme: "advanced",
                            'width':600,
                            'height':400
                        });
                        </script>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input type="Button" class="btn btn-danger right col-sm-2" onclick="add_article()" value="发表文章">  </input>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    function add_article() {

        $title = $("#title").val()
        $content = tinyMCE.activeEditor.getContent()
        if ($title.trim() == "") {
            $("#msg").text("标题不能为空")
            $("#msg").addClass("danger").removeClass("success");
            return;
        } else {
            $("#msg").addClass("success").removeClass("danger");
        }
        if ($content.trim() == "") {
            $("#msg").text("内容不能为空")
            $("#msg").addClass("danger").removeClass("success");
            return;
        } else {
            $("#msg").addClass("success").removeClass("danger");
        }

        $.post("/article/article_add/", {"title": $title, "content": $content, "csrfmiddlewaretoken": "{{ csrf_token }}" }, function (data) {
            if (data.success){
                $("#msg").text(data.msg);
                $("#msg").addClass("success").removeClass("danger");
                $("#title").val("");
                window.location.pathname = "/article/index/"
            } else {
                $("#msg").text("添加失败")
                $("#msg").addClass("danger").removeClass("success");
            }
        }, "json")
    }

</script>
{% endblock %}

test_3/article/templates/article/article_list.html
{% extends 'article/base.html' %}
{% block title%}我的文章{% endblock%}
{% block left %}{% endblock %}

{% block content %}

            <div class="col-md-12">
                <div class="panel panel-primary">
                  <div class="panel-heading">我的文章</div>
                  <div class="panel-body">
                      <table class="table table-hover table-bordered table-striped">
                        <thead>
                            <tr>
                                <td>文章标识</td>
                                <td>文章标题</td>
                                <td>文章简介</td>
                                <td>文章点击量</td>
                                <td>文章操作</td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for at in articles %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="{% url 'article:article_detail' at.id %}">{{at.title|truncatechars:20}}</a></td>
                                <td>{{at.remark|truncatechars:30|safe}}</td>
                                <td> 0 </td>
                                <td>
                                    <a class="btn btn-xs btn-primary" href="{% url 'article:article_update' at.id %}">文章修改</a>
                                    <a class="btn btn-xs btn-danger" onclick="return window.confirm('您确定要删除该文章吗？')" href="{% url 'article:article_delete' at.id %}">文章删除</a>
                                </td>
                            </tr>

                            {% empty %}
                           <tr>
                                <td colspan="7">对不起，目前没有用户， <a href="{% url 'article:article_add' %}">请发表文章</a></td>
                            </tr>
                            {% endfor %}

                        </tbody>
                      </table>
                  </div>
                </div>
            </div>
        </div>

{% endblock %}

test_3/article/templates/article/article_update.html
{% extends 'article/base.html' %}
{% load staticfiles %}
{% block title%}修改文章{% endblock %}

{% block content%}
<div class="col-md-9">
    <div class="panel panel-primary">
        <div class="panel-heading">修改文章</div>
        <div class="panel-body">
            <h4 style="color: red">{{msg}}</h4>

            <form class="form-horizontal" action="{% url 'article:article_update' article.id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">文章标题</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" name="title" id="title" value="{{article.title}}">
                    </div>
                </div>
                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">文章内容</label>
                    <div class="col-md-9">
                        <textarea class="col-sm-9" name="content" id="content"
                                  rows="20">{{article.content|safe}}</textarea>
                        <script type="text/javascript" src="{% static 'article/js/tinymce/tiny_mce.js' %}"></script>
                        <script type="text/javascript">
                        tinyMCE.init({
                            mode: "textareas",
                            theme: "advanced",
                            'width':600,
                            'height':400
                        });

                        </script>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-lg btn-danger">发表文章</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

test_3/article/templates/article/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户博客---{% block title %}首页{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'article/js/lib/bootstrap-3.3.7-dist/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'article/css/common.css' %}">
    <script src="{% static 'article/js/lib/jquery/jquery-1.12.4.js' %}"></script>
    <script src="{% static 'article/js/lib/bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    <style>

    </style>
</head>
<body>

{% block nav %}
<!--导航部分开始-->
<nav class="navbar navbar-default navbar-inverse" id="top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'article:index' %}">项目首页面</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% if request.session.loginUser %}
                <li class="active"><a href="#">欢迎你，<span
                        style="color: red;">{{request.session.loginUser.nickname}} </span></a></li>
                <li><a href="{% url 'article:user_list' %}">查看所有用户</a></li>
                <li><a href="{% url 'article:logout' %}">退出登录</a></li>
                {% else %}
                <li class="active"><a href="{% url 'article:login'%}">登录</a></li>
                <li><a href="{% url 'article:register' %}">注册</a></li>
                {% endif %}
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="请输入您要搜索的关键字">
                </div>
                <button type="submit" class="btn btn-sm btn-default">搜索文章</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if request.session.loginUser %}
                <li><a href="#">{{request.session.loginUser.nickname}}</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">个人中心 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'article:user_info'%}">修改信息</a></li>
                        <li><a href="{% url 'article:psw_update'%}">修改密码</a></li>
                        <li><a href="{% url 'article:upload_avatar'%}">上传头像</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'article:article_add'%}">文章发表</a></li>
                        <li><a href="{% url 'article:article_list'%}">文章管理</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'article:logout' %}">退出登录</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="#">未登录用户</a></li>
                {% endif %}


            </ul>
        </div>
    </div>
</nav>
{% endblock %}
<!--导航部分结束-->

<!--页面主体部分开始-->
<div class="container">
    {% block banner %}
    <div class="page-header">
        <div class="jumbotron" style="padding:0;width:1140px;">
            <div id="myCarousel" class="carousel slide" style="width:1140px;">
                <!-- 轮播（Carousel）指标 -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <!-- 轮播（Carousel）项目 -->
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="{% static 'article/img/back.jpg' %}" alt="First slide">
                    </div>
                    <div class="item">
                        <img src="{% static 'article/img/guidao-009.jpg' %}" alt="Second slide">
                    </div>
                    <div class="item">
                        <img src="{% static 'article/img/guidao-008.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <!-- 轮播（Carousel）导航 -->
                <a class="carousel-control left" href="#myCarousel"
                   data-slide="prev"> <span aria-hidden="true" class="glyphicon glyphicon-chevron-left"></span></a>
                <a class="carousel-control right" href="#myCarousel"
                   data-slide="next"><span aria-hidden="true" class="glyphicon glyphicon-chevron-right"></span></a>
            </div>

        </div>
    </div>
    {% endblock %}
    <div class="row">
        {% block left %}
        <div class="col-md-3">
            <div class="panel panel-primary">
                <div class="panel-heading">用户信息</div>
                <div class="panel-body">
                    <ul class="list-group">
                        {% if request.session.loginUser%}
                        <li class="list-group-item">
                            <img src="/{{request.session.loginUser.avatar}}" alt="用户头像"
                                 class="img-circle avatar center-block ">
                        </li>
                        <li class="list-group-item">
                            用户名称：{{request.session.loginUser.username }}
                        </li>
                        <li class="list-group-item">
                            用户性别：{{request.session.loginUser.gender }}
                        </li>
                        <li class="list-group-item">
                            用户昵称：{{request.session.loginUser.nickname }}
                        </li>
                        {% else %}
                        <li class="list-group-item">
                            <img src="{% static 'article/img/default.gif' %}" alt="用户头像" class="img-circle avatar">
                        </li>
                        <li class="list-group-item">
                            <a href="{% url 'article:login' %}">用户登录</a>
                        </li>
                        <li class="list-group-item">
                            <a href="{% url 'article:register' %}">用户注册</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        {% endblock %}

        {% block content %}
        <div class="col-md-9">
            <div class="panel panel-primary">
                <div class="panel-heading">内容部分</div>
                <div class="panel-body">
                    <h1>内容内</h1>
                </div>
            </div>
        </div>
        {% endblock %}

    </div>


</div>
<!--页面主体部分结束-->

<!--页面尾部开始-->
{% block footer %}
<div class="container">
    <a href="#top" class="back-to-top" style="position:fixed;left:1600px;top:800px"> Back to top </a>
</div>
{% endblock %}
<!--页面尾部结束-->

</body>
</html>

test_3/article/templates/article/login.html
{% extends 'article/base.html' %}
{% block title%}用户登录{% endblock%}

{% block content %}
<div class="col-md-9">
    <div class="panel panel-primary">
        <div class="panel-heading">用户登录</div>
        <div class="panel-body">
            <h4 style="color: red">{{msg}}</h4>

            <form class="form-horizontal" action="{% url 'article:login'%}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">用户名称</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="username" id="username" placeholder="请输入您的用户名称">
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">用户密码</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" name="password" id="password"
                               placeholder="请输入您的用户密码">
                    </div>
                </div>
                {% if request.session.display %}
                <div class="form-group">
                    <label for="verify_code" class="col-sm-2 control-label">验证码</label>
                    <div class="col-md-10">
                        <div class="col-md-4 col-md-offset-0">
                            <input type="text" class="form-control col-md-7" name="verify_code" id="verify_code"
                               placeholder="请输入验证码">
                        </div>
                        <img src="/article/code/" alt="换一张" id="verify_pic">
                        <script>
                        $(document).ready(function () {
                            var img = document.getElementById('verify_pic');
                            img.onclick=function(){
                                  $(this).attr("src", "/article/code/?id"+Math.random())
                                }
                        });
                        </script>
                    </div>
                </div>
                {% endif %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-lg btn-danger">用户登录</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock%}

test_3/article/templates/article/user_list.html
{% extends 'article/base.html' %}
{% block title%}用户列表{% endblock%}

{% block content %}

<div class="col-md-9">
    <div class="panel panel-primary">
        <div class="panel-heading">用户注册</div>
        <div class="panel-body">
            <table class="table table-hover table-bordered table-striped">
                <thead>
                <tr>
                    <td>用户标识</td>
                    <td>用户名称</td>
                    <td>用户昵称</td>
                    <td>用户性别</td>
                    <td>用户邮箱</td>
                    <td>用户年龄</td>
                    <td>用户操作</td>
                </tr>
                </thead>
                <tbody>
                {% for u in users %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'article:user_info' %}">{{u.username}}</a></td>
                    <td><a href="{% url 'article:user_info' %}">{{u.nickname}}</a></td>
                    <td>{{u.gender}}</td>
                    <td>{{u.email}}</td>
                    <td>{{u.age}}</td>
                    <td>
                        <a class="btn btn-xs btn-primary" href="{% url 'article:user_update' %}?id={{u.id}}">用户修改</a>
                        <a class="btn btn-xs btn-danger" onclick="return window.confirm('您确定要删除该用户吗？')"
                           href="{% url 'article:user_delete' u.id %}">用户删除</a>
                    </td>
                </tr>

                {% empty %}
                <tr>
                    <td colspan="7">对不起，目前没有用户， <a href="{% url 'article:register' %}">请注册</a></td>
                </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>
</div>

{% endblock %}