day08/mysite/blog/urls.py
from django.conf.urls import url

from . import views


# app_name = "blog"

urlpatterns = [
    url(r'^index/$', views.index, name="index"),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^user_list/$', views.user_list, name="user_list"),
    url(r'^register/$', views.register, name="register"),
    url(r'^user_update/$', views.user_update, name="user_update"),
    url(r'^(\d+)/user_info/$', views.user_info, name="user_info"),
    url(r'^(?P<user_id>\d+)/user_delete/$', views.user_delete, name="user_delete"),

    url(r"^article_add/$", views.article_add, name="article_add"),
    url(r"^article_delete/(?P<a_id>\d+)/$", views.article_delete, name="article_delete"),
    url(r"^article_update/(?P<a_id>\d+)/$", views.article_update, name="article_update"),
    url(r"^article_detail/(?P<a_id>\d+)/$", views.article_detail, name="article_detail"),
    url(r"^list_self/$", views.list_self, name="list_self"),
    url(r"^code/$", views.code, name="code"),
    # url(r"^hello_ajax/$", views.hello_ajax, name="hello_ajax"),
    # url(r"^hello_ajax_jquery/$", views.hello_ajax_jquery, name="hello_ajax_jquery"),
    url(r"^checkusername/$", views.checkusername, name="checkusername"),
    url(r"^test/$", views.test, name="test"),
]

day08/mysite/mysite/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    url(r"^blog/", include("blog.urls", namespace="blog")),
    url(r'^admin/', admin.site.urls),
]

day08/mysite/blog/models.py
from datetime import datetime

from django.db import models
from tinymce.models import HTMLField


class User(models.Model):
    """
        博客用户类
    """
    id = models.AutoField(primary_key=True, verbose_name="用户主键")
    username = models.CharField(max_length=100, unique=True, verbose_name="用户名称")
    password = models.CharField(max_length=255, verbose_name="用户密码")
    nickname = models.CharField(max_length=255, default="普通用户", verbose_name="用户昵称")
    age = models.IntegerField(default=18, verbose_name="用户年龄")
    gender = models.CharField(max_length=10, default="女", verbose_name="用户性别")
    email = models.CharField(max_length=255, null=True, blank=True, verbose_name="用户邮箱")
    avatar = models.ImageField(upload_to="static/headers/", default="static/headers/default.jpg", verbose_name="用户头像")
    tel = models.CharField(max_length=50, default="110", verbose_name="用户头像")

    def __str__(self):
        return self.nickname


class Article(models.Model):
    """ 文章类"""
    id = models.AutoField(primary_key=True, verbose_name="文章主键")
    title = models.CharField(max_length=100, verbose_name="文章标题")
    # content = models.TextField(verbose_name="文章内容")
    content = HTMLField(verbose_name="文章内容")
    remark = models.CharField(max_length=255, default="", verbose_name="文章摘要")
    publishTime = models.DateTimeField(auto_now_add=True, verbose_name="文章发表时间")
    modifyTime = models.DateTimeField(auto_now=True, verbose_name="文章修改时间")
    count = models.IntegerField(default=0, verbose_name="文章点击量")
    # 文章作者，也就是用户对象
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ["-publishTime"]

    def __str__(self):
        return self.title

day08/mysite/blog/views.py
import time
from io import BytesIO
import logging

from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, JsonResponse
from django.core.cache import cache
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST, require_GET, require_safe, require_http_methods
from django.forms.models import model_to_dict
from django.core.serializers import serialize
from django.core.paginator import Paginator
from django.conf import settings

from . import models
from . import utils
from . import cacheUtil
# from .tasks import add

def index(request):
    logger = logging.getLogger("django")
    logger.info("首页开始加载数据量……")
    # add.delay()
    # 分页功能
    pageNow = int(request.GET.get("pageNow", 1))
    pageSize = settings.PAGE_SIZE
    ats = cacheUtil.getAllArticle()
    # 第一个参数是需要分页的数据列表，第二个参数是每页的数量
    paginator = Paginator(ats, pageSize)
    # page需要参数的当前页
    page = paginator.page(pageNow)
    return render(request, "index.html", {"page": page})


def register(request):
    """ 用户注册功能
    """
    if request.method == "GET":
        return render(request, "blog/register.html", {"msg": "请认真填写如下选项"})
    elif request.method == "POST":
        username = request.POST["username"].strip()
        password = request.POST.get("password")
        confirmpwd = request.POST["confirmpwd"]
        nickname = request.POST["nickname"]
        avatar = request.FILES["avatar"]

        # 数据校验
        if username == "":
            return render(request, "blog/register.html", {"msg": "用户名称不能为空"})
        if len(password) < 3:
            return render(request, "blog/register.html", {"msg": "用户密码长度不能小于3位"})
        if password.strip() != confirmpwd.strip():
            return render(request, "blog/register.html", {"msg": "两次密码不一致"})
        if nickname == "":
            return render(request, "blog/register.html", {"msg": "用户昵称不能为空"})

        # 用户名称不能重复
        try:
            models.User.objects.get(username=username)
            return render(request, "blog/register.html", {"msg": "该用户名称已经存在，请重新输入"})
        except:
            try:
                # 进行密码加密
                password = utils.md5_by_hmac(password)
                if avatar is None:
                    user = models.User(username=username, password=password, nickname=nickname)
                    user.save()
                else:
                    user = models.User(username=username, password=password, nickname=nickname, avatar=avatar)
                    user.save()
            except:
                return render(request, "blog/register.html", {"msg": "注册失败，请重新注册"})

        return render(request, "blog/login.html", {"msg": "用户注册成功！！，请登录"})


def login(request):
    """ 用户登录功能
    """
    if request.method == "GET":
        return render(request, "blog/login.html", {"msg": "请认真填写如下选项"})
    else:
        # 接受页面的参数
        username = request.POST["username"].strip()
        password = request.POST["password"].strip()
        code = request.POST["code"].strip()

        # 数据校验
        if code.lower() != request.session["code"].lower():
            return render(request, "blog/login.html", {"msg": "验证码错误！！"})
        if username == "":
            return render(request, "blog/login.html", {"msg": "用户名称不能为空"})
        if password == "":
            return render(request, "blog/login.html", {"msg": "用户密码不能为空"})

        users = models.User.objects.filter(username=username)
        if len(users) > 0:
            # 加密密码
            password = utils.md5_by_hmac(password)
            if users[0].password == password:
                # 登录成功，需要保持用户的信息，以表示用户已经登录
                request.session["loginUser"] = users[0]
                # 比如说跳转用户列表页面
                # return HttpResponseRedirect("/blog/user_list/")
                # return redirect("/blog/user_list/")
                response = redirect(reverse("blog:user_list"))
                response.set_cookie("isLogin", True, max_age=3600*24*14)
                return response
            else:
                return render(request, "blog/login.html", {"msg": "密码错误！！"})
        else:
            return render(request, "blog/login.html", {"msg": "该用户名不存在！！"})


@utils.requirelogin
def logout(request):
    """用户退出"""
    try:
        del request.session["loginUser"]
        return render(request, "blog/login.html", {"msg": "用户退出成功，请重新登录！！"})
    except:
        return render(request, "blog/login.html", {"msg": "用户退出成功，请重新登录！！"})


@utils.requirelogin
def user_list(request):
    users = models.User.objects.all()
    return render(request, "blog/user_list.html", {"users": users})


@utils.requirelogin
def user_update(request):
    if request.method == "GET":
        id = request.GET["id"]
        user  = models.User.objects.get(pk=id)
        return render(request, "blog/user_update.html", {"users": user})
    else:
        id = request.POST["id"]
        nickname = request.POST["nickname"]
        age = request.POST["age"]
        gender = request.POST["gender"]
        email = request.POST["email"]

        user = models.User.objects.get(pk=id)
        user.nickname = nickname
        user.age = age
        user.gender = gender
        user.email = email

        user.save()
        # return redirect("/blog/user_list/")
        # return redirect(reverse("blog:user_list", kwargs={"user_id": 2233}))
        # return redirect(reverse("blog:user_list", args=(1,)))
        return redirect(reverse("blog:user_list"))


@utils.requirelogin
def user_delete(request, user_id):
    user = models.User.objects.get(pk=user_id)
    user.delete()
    # return redirect("/blog/user_list/")
    return redirect(reverse("blog:user_list"))


def user_info(request, u_id):
    user = models.User.objects.get(id=u_id)
    return render(request, "blog/user_info.html", {"users": user})


@utils.requirelogin
# @csrf_exempt
def article_add(request):
    if request.method == "GET":
        return render(request, "blog/article_add.html", {})
    elif request.method == "POST":
        title = request.POST["title"].strip()
        content = request.POST["content"].strip()
        remark = utils.removeHTMLByRE(content)[:50]
        author = request.session["loginUser"]

        # 验证
        if title == "":
            return render(request, "blog/article_add.html", {"msg": "文字标题不能为空！"})
        if content == "":
            return render(request, "blog/article_add.html", {"msg": "文字内容不能为空！"})

        at = models.Article(title=title, content=content, remark=remark, author=author)
        at.save()
        # 更新缓存
        cacheUtil.getAllArticle(ischange=True)
        # return redirect(reverse("blog:article_detail", kwargs={"a_id": at.id}))
        return JsonResponse({"msg": "文章添加成功", "success": True})


@utils.requirelogin
def article_delete(request, a_id):
    at = models.Article.objects.get(pk=a_id)
    at.delete()
    # 更新缓存
    cacheUtil.getAllArticle(ischange=True)
    return redirect(reverse("blog:list_self"))


@utils.requirelogin
def article_update(request, a_id):
    at = models.Article.objects.get(id=a_id)
    if request.method == "GET":
        return render(request, "blog/article_update.html", {"article": at})
    else:
        title = request.POST["title"].strip()
        content = request.POST["content"].strip()
        remark = utils.removeHTMLByRE(content)[:50]
        # 验证
        if title == "":
            return render(request, "blog/article_update.html", {"article": at, "msg": "文字标题不能为空！"})
        if content == "":
            return render(request, "blog/article_update.html", {"article": at, "msg": "文字内容不能为空！"})

        at = models.Article.objects.get(pk=a_id)
        at.title = title
        at.content = content
        at.remark = remark
        at.save()

        # 更新缓存
        cacheUtil.getAllArticle(ischange=True)
        return redirect(reverse("blog:article_detail", kwargs={"a_id": at.id}))


def article_detail(request, a_id):
    at = models.Article.objects.get(pk=a_id)
    return render(request, "blog/article_detail.html", {"article": at})


@utils.requirelogin
def list_self(request):
    # ats = models.Article.objects.filter(author=request.session["loginUser"])
    # return render(request, "blog/list_self.html", {"articles": ats})
    return render(request, "blog/list_self.html", {})


def code(request):
    img, msg = utils.create_code()

    f = BytesIO()
    img.save(f, "PNG")

    # 将验证码的值存储到session
    request.session["code"] = msg

    return HttpResponse(f.getvalue(), "image/png")



# @csrf_exempt # 表示该视图函数忽略csrf验证
# # @require_POST
# # @require_http_methods(["GET","POST"])
# # @require_safe
# @require_GET
# def hello_ajax(request):
#     print("id=", request.POST["id"])
#     return HttpResponse("hello ajax")


# @require_GET
# def hello_ajax_jquery(request):
    # res = {"id": 10}
    # # 如果返回的是字典对象，需要使用JsonResponse
    # return JsonResponse(res)
    # res = "{\"id\": 10}"
    # return HttpResponse(res, "application/json")
    # id = request.GET['id']
    # users = models.User.objects.get(pk=id)
    # model_to_dict 该方法，真能使用在我们model转换为字典对象的时候
    # res = model_to_dict(users)
    # print(res)
    # res = {"users": users}
    # return JsonResponse(res)

    # ats = models.Article.objects.all()
    # # serialize 会根据第一个参数将queryset序列化为一个字符串
    # res = serialize("json", ats)
    # return HttpResponse(res, "application/json")
    #
    # ats = models.Article.objects.values("id", "title","content")
    # return HttpResponse(ats)


@csrf_exempt
@require_POST
def checkusername(request):
    username = request.POST["username"]
    try:
        models.User.objects.get(username=username)
        return JsonResponse({"msg": "对不起，该账户已经存在，请重新注册", "success": False})
    except:
        return JsonResponse({"msg": "恭喜你，该账户可以使用", "success": True})


def test(request):
    response = HttpResponse("hello world")
    response.set_cookie("username", "liujianhong", max_age=3600*24*14)

    return response

day08/mysite/templates/blog/article_add.html
{% extends 'base.html' %}

{% block title%}发表文章{% endblock %}

{% block content%}
<div class="col-md-9">
    <div class="panel panel-primary">
        <div class="panel-heading">用户发表文章</div>
        <div class="panel-body">
            <h4 style="color: red" id="msg">{{msg}}</h4>

            <!--<form class="form-horizontal" action="{% url 'blog:article_add'%}" method="post">-->
                {% csrf_token %}
                <div class="form-group">
                    <div class="col-sm-10  col-sm-offset-1">
                        <input type="text" class="form-control" name="title" id="title" placeholder="请输入发表文章的标题">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-10 col-sm-offset-1">
                        <textarea class="" name="content" id="content" rows="20" placeholder="请输入文章内容"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" onclick="add_article()" class="btn btn-lg btn-danger">发表文章</button>
                    </div>
                </div>
            <!--</form>-->
        </div>
    </div>
</div>
<script type="text/javascript" src="/static/tiny_mce/tiny_mce.js"></script>

<script>
    tinyMCE.init({
         "mode": 'textareas',
        "theme": "advanced",
        "width": 700,
        "height": 400,
    })



    function add_article() {

        $title = $("#title").val()
        $content = tinyMCE.activeEditor.getContent()
        if ($title.trim() == "") {
            $("#msg").text("标题不能为空")
            $("#msg").addClass("danger").removeClass("success");
            return;
        } else {
            $("#msg").addClass("success").removeClass("danger");
        }
        if ($content.trim() == "") {
            $("#msg").text("内容不能为空")
            $("#msg").addClass("danger").removeClass("success");
            return;
        } else {
            $("#msg").addClass("success").removeClass("danger");
        }

        $.post("/blog/article_add/", {"title": $title, "content": $content, "csrfmiddlewaretoken": "{{ csrf_token }}" }, function (data) {
            if (data.success){
                $("#msg").text(data.msg)
                $("#msg").addClass("success").removeClass("danger");

                $("#title").val("");
                tinyMCE.activeEditor.setContent("");
//                window.location.pathname = "/blog/index/"
            } else {
                $("#msg").text("添加失败")
                $("#msg").addClass("danger").removeClass("success");
            }
        }, "json")


    }

</script>

{% endblock %}

day08/mysite/templates/blog/article_detail.html
{% extends 'base.html' %}

{% block title%}文章详情{% endblock %}
{% block left %}{% endblock %}


{% block content%}
<div class="col-md-12">
    <div class="panel panel-primary">
        <div class="panel-heading">文章详情</div>
        <div class="panel-body">
            <h1 class="text-center">{{ article.title }} </h1>
            <h4 class="text-right">作者：{{article.author.nickname}}|
                    发表时间：{{article.publishTime}}|
                    修改时间：{{article.modifyTime}}
            </h4>
            <div class="panel panel-primary">
                <div class="panel-body">
                   {# {{article.content | safe }} #}
                    {% autoescape off%}
                        {{article.content}}
                    {% endautoescape %}
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

day08/mysite/templates/blog/article_update.html
{% extends 'base.html' %}

{% block title%}修改文章{% endblock %}

{% block content%}
<div class="col-md-9">
    <div class="panel panel-primary">
        <div class="panel-heading">修改文章</div>
        <div class="panel-body">
            <h4 style="color: red">{{msg}}</h4>

            <form class="form-horizontal" action="{% url 'blog:article_update' article.id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="col-sm-10  col-sm-offset-1">
                        <input type="text" class="form-control" name="title" id="title" value="{{article.title}}">
                    </div>
                </div>
                <div class="form-group">
                    <textarea class="col-sm-10 col-sm-offset-1" name="content" id="content" rows="20" >{{article.content}}</textarea>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-lg btn-danger">发表文章</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

day08/mysite/templates/blog/list_self.html
{% extends 'base.html' %}
{% block title%}我的文章{% endblock%}
{% block left %}{% endblock %}

{% block content %}

            <div class="col-md-12">
                <div class="panel panel-primary">
                  <div class="panel-heading">我的文章</div>
                  <div class="panel-body">
                      <table class="table table-hover table-bordered table-striped">
                        <thead>
                            <tr>
                                <td>文章标识</td>
                                <td>文章标题</td>
                                <td>文章简介</td>
                                <td>文章点击量</td>
                                <td>文章操作</td>
                            </tr>
                        </thead>
                        <tbody>
                          {#  {% for at in articles %} #}
                          {% for at in request.session.loginUser.article_set.all %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="{% url 'blog:article_detail' at.id %}">{{at.title|truncatechars:20}}</a></td>
                                <td>{{at.remark|truncatechars:30}}</td>
                                <td> 0 </td>
                                <td>
                                    <a class="btn btn-xs btn-primary" href="{% url 'blog:article_update' at.id %}">文章修改</a>
                                    <a class="btn btn-xs btn-danger" onclick="return window.confirm('您确定要删除该用户吗？')" href="{% url 'blog:article_delete' at.id %}">文章删除</a>
                                </td>
                            </tr>

                            {% empty %}
                           <tr>
                                <td colspan="7">对不起，目前没有用户， <a href="{% url 'blog:article_add' %}">请发表文章</a></td>
                            </tr>
                            {% endfor %}

                        </tbody>
                      </table>
                  </div>
                </div>
            </div>
        </div>

{% endblock %}

day08/mysite/templates/blog/login.html
{% extends 'base.html' %}
{% block title%}用户登录{% endblock%}

{% block content %}
<div class="col-md-9">
    <div class="panel panel-primary">
        <div class="panel-heading">用户登录</div>
        <div class="panel-body">
            <h4 style="color: red">{{msg}}</h4>

            <form class="form-horizontal" action="{% url 'blog:login'%}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">用户名称</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="username" id="username" placeholder="用输入您的用户名称">
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">用户密码</label>
                    <div class="col-sm-10">
                         <input type="password" class="form-control" name="password" id="password"
                           placeholder="用输入您的用户密码">
                    </div>
                </div>
                <div class="form-group">
                    <label for="code" class="col-sm-2 control-label">验证码</label>
                    <div class="col-sm-6">
                         <a href="#" title="点击刷新" onclick="code()">
                             <img src="/blog/code/" alt="验证码" id="code" >
                             <input type="text"  name="code" autocomplete="off">
                         </a>
                    </div>
                    <div class="col-sm-4">
                        <a href="#" title="点击刷新" onclick="code()">点击刷新</a>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-lg btn-danger">用户登录</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
        function code() {
            img = document.getElementById("code");
            img.src = "/blog/code/?id=" + new Date().getTime()
//            img.src = "/blog/code/?id=" + Math.random()
        }

</script>

{% endblock%}

day08/mysite/templates/blog/register.html
{% extends 'base.html' %}
{% block title%}用户注册{% endblock%}

{% block content %}
<div class="col-md-9">
    <div class="panel panel-primary">
        <div class="panel-heading">用户注册</div>
        <div class="panel-body">
            <h4 style="color: red" id="msg">{{msg}}</h4>

            <form class="form-horizontal" action="{% url 'blog:register'%}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">用户名称</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="username" id="username" placeholder="用输入您的用户名称">
                    </div>
                </div>
                <div class="form-group">
                    <label for="avater" class="col-sm-2 control-label">用户头像</label>
                    <div class="col-sm-10">
                        <input type="file" class="form-control" name="avatar">
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">用户密码</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" name="password" id="password"
                               placeholder="用输入您的用户密码">
                    </div>
                </div>
                <div class="form-group">
                    <label for="confirmpwd" class="col-sm-2 control-label">确认密码</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" name="confirmpwd" id="confirmpwd"
                               placeholder="请确认您的密码">
                    </div>
                </div>
                <div class="form-group">
                    <label for="nickname" class="col-sm-2 control-label">用户昵称</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="nickname" id="nickname"
                               placeholder="用输入您的用户昵称（可以是中文）">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" disabled class="btn btn-lg btn-danger submit-btn">用户注册</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
</div>
<script>
    $(function () {
       $("#username").on("blur", function () {
           username = $(this).val()
           if (username.trim() == "") {
               $("#msg").text("用户名称不能为空");
               $(".submit-btn").attr("disabled", "disabled")
               return;
           }

           $.ajax({
               url: "/blog/checkusername/",
               "type": "POST",
               "data": {"username": username},
               dataType: "json",
               success: function (data) {
                   if (data.success) {
                       $("#msg").text(data.msg);
                        $(".submit-btn").removeAttr("disabled")
                   } else {
                       $("#msg").text(data.msg);
                       $(".submit-btn").attr("disabled", "disabled")
                   }
               }
           })



       });


    });

</script>

{% endblock %}

day08/mysite/templates/blog/user_list.html
{% extends 'base.html' %}
{% block title%}用户列表{% endblock%}

{% block content %}

            <div class="col-md-9">
                <div class="panel panel-primary">
                  <div class="panel-heading">用户注册</div>
                  <div class="panel-body">
                      <table class="table table-hover table-bordered table-striped">
                        <thead>
                            <tr>
                                <td>用户标识</td>
                                <td>用户名称</td>
                                <td>用户昵称</td>
                                <td>用户性别</td>
                                <td>用户邮箱</td>
                                <td>用户年龄</td>
                                <td>用户操作</td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for u in users %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="{% url 'blog:user_info' u.id %}">{{u.username}}</a></td>
                                <td><a href="{% url 'blog:user_info' u.id %}">{{u.nickname}}</a></td>
                                <td>{{u.gender}}</td>
                                <td>{{u.email}}</td>
                                <td>{{u.age}}</td>
                                <td>
                                    <a class="btn btn-xs btn-primary" href="{% url 'blog:user_update' %}?id={{u.id}}">用户修改</a>
                                    <a class="btn btn-xs btn-danger" onclick="return window.confirm('您确定要删除该用户吗？')" href="{% url 'blog:user_delete' u.id %}">用户删除</a>
                                </td>
                            </tr>

                            {% empty %}
                           <tr>
                                <td colspan="7">对不起，目前没有用户， <a href="{% url 'blog:register' %}">请注册</a></td>
                            </tr>
                            {% endfor %}

                        </tbody>
                      </table>
                  </div>
                </div>
            </div>
        </div>

{% endblock %}

day08/mysite/templates/blog/user_update.html
{% extends 'base.html' %}
{% block title%}用户信息修改{% endblock%}

{% block content %}


            <div class="col-md-9">
                <div class="panel panel-primary">
                  <div class="panel-heading">用户信息修改</div>
                  <div class="panel-body">
                       <h4 style="color: red">{{msg}}</h4>

                      <form class="form-horizontal" action="{% url 'blog:user_update'%}" method="post">
                          {% csrf_token %}
                          <input type="hidden" name="id" value="{{user.id}}">

                          <div class="form-group">
                            <label for="username" class="col-sm-2 control-label">用户名称</label>
                            <div class="col-sm-10">
                              <input type="text" class="form-control" disabled name="username" id="username" value="{{user.username}}">
                            </div>
                          </div>
                          <div class="form-group">
                            <label for="nickname"  class="col-sm-2 control-label">用户昵称</label>
                            <div class="col-sm-10">
                              <input type="text" class="form-control" required name="nickname" id="nickname" value="{{user.nickname}}">
                            </div>
                          </div>
                          <div class="form-group">
                            <label for="age" class="col-sm-2 control-label">用户年龄</label>
                            <div class="col-sm-10">
                              <input type="number" class="form-control" name="age" id="age" value="{{user.age}}">
                            </div>
                          </div>
                          <div class="form-group">
                            <label for="email" class="col-sm-2 control-label">用户邮箱</label>
                            <div class="col-sm-10">
                              <input type="email" class="form-control" name="email" id="email" value="{{user.email}}">
                            </div>
                          </div>
                          <div class="form-group">
                            <label  class="col-sm-2 control-label">用户性别</label>
                            <div class="col-sm-10">
                                {% if user.gender == '男' %}
                                <input type="radio" name="gender" value="男" checked>男
                                <input type="radio" name="gender"  value="女">女
                                {% elif user.gender == "女" %}
                                 <input type="radio" name="gender"  value="男" >男
                                <input type="radio" name="gender" value="女" checked>女
                                {% endif %}
                            </div>
                          </div>
                          <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                              <button type="submit" class="btn btn-lg btn-danger">用户修改</button>
                            </div>
                          </div>
                        </form>
                  </div>
                </div>
            </div>
        </div>
{% endblock %}