test_1/db_static/urls.py
from django.conf.urls import url
from . import models,views

app_name="db_static"
urlpatterns=[
    url(r'^home/$',views.home,name="home"),
    url(r'^reg/$',views.reg,name="reg"),
    url(r"^doReg/$", views.doReg, name="doReg"),
    url(r'^login/$', views.login, name="login"),
    url(r'^doLogin/$', views.doLogin, name="doLogin"),
    url(r'^info/$', views.info, name="info"),
    url(r'^changeInfo/$',views.changeInfo,name="changeInfo"),
    url(r'^doChangeInfo/$', views.doChangeInfo, name="doChangeInfo"),
    url(r'^changePsw/$',views.changePsw,name="changePsw"),
    url(r'^doChangePsw/$',views.doChangePsw,name="doChangePsw"),
    url(r'^users/$',views.users,name="users"),
    url(r'^delete/$', views.delete, name="delete"),
    url(r'^doDelete/$', views.doDelete, name="doDelete"),
]

test_1/test_1/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r"^db_static/", include("db_static.urls")),
]

test_1/db_static/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    id=models.AutoField(primary_key=True,unique=True)
    name=models.CharField(max_length=20,unique=True)
    psw=models.CharField(max_length=20,)
    gender=models.CharField(max_length=5,)
    age = models.IntegerField()
    address=models.CharField(max_length=255,null=True)

test_1/db_static/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from django.template import RequestContext
import json

from . import models


# Create your views here.

def home(request):
    # print(request.session["now"])
    # context={request.session.get("now"),}
    return render(request, 'db_static/home.html')


def reg(request):
    # return render(request, 'db_static/reg.html',context_instance=RequestContext(request))
    return render(request, 'db_static/reg.html')


# @csrf_protect
def doReg(request):
    name = request.POST["name"]
    psw = request.POST["psw"]
    age = int(request.POST["age"])
    gender = request.POST["gender"]
    address = request.POST["address"]
    try:
        oldName=models.User.objects.get(name=name)
        return render(request, "db_static/reg_fail.html")
    except:
        if len(address) == 0:
            try:
                user = models.User(name=name, psw=psw, age=age, gender=gender)
                user.save()
                return render(request, "db_static/reg_success.html")
            except:
                return render(request, "db_static/reg_fail.html")
        else:
            try:

                user = models.User(name=name, psw=psw, age=age, gender=gender, address=address)
                user.save()

                return render(request, "db_static/reg_success.html")
            except:
                return render(request, "db_static/reg_fail.html")


def login(request):
    return render(request, 'db_static/login.html')


# @csrf_protect
def doLogin(request):
    name = request.POST["name"]
    psw = request.POST["psw"]
    user = models.User.objects.get(name=name)
    request.session.set_expiry(0)
    if user.psw == psw:
        request.session.clear()
        request.session['now'] = name
        return render(request, 'db_static/login_success.html', )
    else:
        return render(request, 'db_static/login_fail.html')


# 查看当前用户信息
def info(request):
    name = request.session.get("now")
    # print(name)
    # 不存在时返回值是none
    if name != None:
        user = models.User.objects.get(name=name)
        context = {
            "name": user.name,
            "age": user.age,
            "gender": user.gender,
            "address": user.address,
        }
        return render(request, 'db_static/info_show.html', context=context)
    else:
        return render(request, 'db_static/info_fail.html')


# 修改当前用户信息
def changeInfo(request):
    name = request.session.get("now")
    # print(name)
    # 不存在时返回值是none
    if name != None:
        user = models.User.objects.get(name=name)
        context = {
            "name": user.name,
            "age": user.age,
            "gender": user.gender,
            "address": user.address,
        }
        return render(request, 'db_static/change_info.html', context=context)
    else:
        return render(request, 'db_static/info_fail.html')


def doChangeInfo(request):
    name = request.session.get("now")
    changeWhat = request.POST["changeWhat"]
    result = request.POST["result"]
    user = models.User.objects.get(name=name)
    try:
        if changeWhat == "gender":
            user.gender = result
        elif changeWhat == "age":
            user.age = int(result)
        elif changeWhat == "address":
            user.age = result
        user.save()
        return render(request, "db_static/change_info_success.html")
    except:
        return render(request, "db_static/change_info_fail.html")


# 修改当前用户密码
def changePsw(request):
    name = request.session.get("now")
    if name != None:
        return render(request, 'db_static/change_psw.html')
    else:
        return render(request, 'db_static/info_fail.html')


def doChangePsw(request):
    name = request.session.get("now")
    user = models.User.objects.get(name=name)
    psw = request.POST["psw"]
    psw_confirm = request.POST["psw_confirm"]
    if psw != user.psw:
        if psw == psw_confirm:
            return render(request, 'db_static/change_psw_success.html')
        else:
            return render(request, 'db_static/change_psw_fail.html')
    else:
        return render(request, 'db_static/change_psw_fail.html')

# 查看用户列表
def users(request):
    users=models.User.objects.all()
    usersList=[]
    for i in users:
        usersList.append(i.name)
    return render(request,'db_static/users.html',{'List': json.dumps(usersList),})

# 删除当前用户
def delete(request):
    name = request.session.get("now")
    if name != None:
        user = models.User.objects.get(name=name)
        context = {
            "name": user.name,
            "age": user.age,
            "gender": user.gender,
            "address": user.address,
        }
        return render(request, 'db_static/delete.html',context=context)
    else:
        return render(request, 'db_static/info_fail.html')

def doDelete(request):
    name = request.session.get("now")
    if name != None:
        user = models.User.objects.get(name=name)
        user.delete()
        return render(request, 'db_static/delete_success.html')
    else:
        return render(request, 'db_static/info_fail.html')

test_1/db_static/templates/db_static/change_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'db_static/css/info.css' %}">
</head>
<body>
<div id="info_div">
    <table class="hovertable">
        <caption>{{name}}</caption>
        <tr onmouseover="this.style.backgroundColor='#ccccff';" onmouseout="this.style.backgroundColor='#d4e3e5';">
            <td>name:</td>
            <td>{{name}}</td>
        </tr>
        <tr onmouseover="this.style.backgroundColor='#ccccff';" onmouseout="this.style.backgroundColor='#d4e3e5';">
            <td>age</td>
            <td>{{age}}</td>
        </tr>
        <tr onmouseover="this.style.backgroundColor='#ccccff';" onmouseout="this.style.backgroundColor='#d4e3e5';">
            <td>gender</td>
            <td>{{gender}}</td>
        </tr>
        <tr onmouseover="this.style.backgroundColor='#ccccff';" onmouseout="this.style.backgroundColor='#d4e3e5';">
            <td>address</td>
            <td>{{address}}</td>
        </tr>
    </table>
    <form action="{% url 'db_static:doChangeInfo' %}" method='post'>
        <select name='changeWhat'>
            <option value=age>age</option>
            <option value=gender>gender</option>
            <option value=address>address</option>
        </select>
        修改为：<input type='text' name='result'>
        <button type='submit'>确定</button>
    </form>

</div>
</body>
</html>

test_1/db_static/templates/db_static/change_info_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'db_static/css/reg.css' %}">
</head>
<body>
    <div id="reg">
        <h1> Info changed Successfully </h1>

    </div>

    <div id="time">
        <h2><span id="sp">5</span>seconds later skip to home page...</h2>
            <script>
                onload=function () {
                    setInterval(go,1000)
                };
                var x=4;
                function go() {

                    if (x>=0){
                        document.getElementById("sp").innerText=x;
                    }else {
                        location.href="{% url 'db_static:home' %}";
                    }
                    x--;
                }
            </script>
    </div>


</body>
</html>

test_1/db_static/templates/db_static/change_psw.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'db_static/css/reg.css' %}">
</head>
<body>
    <div id="reg">
        <h1>Login</h1>
        <form action="{% url 'db_static:doChangePsw' %}" method="post">
            <input type="password" required="required" placeholder="new password:" name="psw">
            <input type="password" required="required" placeholder="please input it again:" name="psw_confirm">
            <button class="button_1" type="submit">确定</button>
        </form>
    </div>
</body>
</html>

test_1/db_static/templates/db_static/change_psw_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'db_static/css/reg.css' %}">
</head>
<body>
    <div id="reg">
        <h1> Something wrong happened</h1>

    </div>
    <div id="time">
        <h2><span id="sp">5</span>seconds later skip to change password page...</h2>
            <script>
                onload=function () {
                    setInterval(go,1000)
                };
                var x=4;
                function go() {

                    if (x>=0){
                        document.getElementById("sp").innerText=x;
                    }else {
                        location.href="{% url 'db_static:changePsw' %}";
                    }
                    x--;
                }
            </script>
    </div>
</body>
</html>

test_1/db_static/templates/db_static/change_psw_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'db_static/css/reg.css' %}">
</head>
<body>
    <div id="reg">
        <h1> Password changed Successfully </h1>

    </div>

    <div id="time">
        <h2><span id="sp">5</span>seconds later skip to home page...</h2>
            <script>
                onload=function () {
                    setInterval(go,1000)
                };
                var x=4;
                function go() {

                    if (x>=0){
                        document.getElementById("sp").innerText=x;
                    }else {
                        location.href="{% url 'db_static:home' %}";
                    }
                    x--;
                }
            </script>
    </div>


</body>
</html>

test_1/db_static/templates/db_static/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'db_static/css/info.css' %}">
</head>
<body>
<div id="info_div">
    <table class="hovertable">
        <caption>{{name}}</caption>
        <tr onmouseover="this.style.backgroundColor='#ccccff';" onmouseout="this.style.backgroundColor='#d4e3e5';">
            <td>name:</td>
            <td>{{name}}</td>
        </tr>
        <tr onmouseover="this.style.backgroundColor='#ccccff';" onmouseout="this.style.backgroundColor='#d4e3e5';">
            <td>age</td>
            <td>{{age}}</td>
        </tr>
        <tr onmouseover="this.style.backgroundColor='#ccccff';" onmouseout="this.style.backgroundColor='#d4e3e5';">
            <td>gender</td>
            <td>{{gender}}</td>
        </tr>
        <tr onmouseover="this.style.backgroundColor='#ccccff';" onmouseout="this.style.backgroundColor='#d4e3e5';">
            <td>address</td>
            <td>{{address}}</td>
        </tr>
    </table>
    <form action="{% url 'db_static:doDelete' %}" method='post'>
        Are you sure to delete your account?
        <br><button type='submit'>sure</button>
    </form>
</div>
</body>
</html>

test_1/db_static/templates/db_static/delete_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'db_static/css/reg.css' %}">
</head>
<body>
    <div id="reg">
        <h1> Account deleted Successfully </h1>

    </div>

    <div id="time">
        <h2><span id="sp">5</span>seconds later skip to home page...</h2>
            <script>
                onload=function () {
                    setInterval(go,1000)
                };
                var x=4;
                function go() {

                    if (x>=0){
                        document.getElementById("sp").innerText=x;
                    }else {
                        location.href="{% url 'db_static:home' %}";
                    }
                    x--;
                }
            </script>
    </div>


</body>
</html>

test_1/db_static/templates/db_static/home.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
        {% load staticfiles %}
		<script src="{% static 'db_static/js/jquery-2.1.4.js' %}" type="text/javascript" charset="utf-8"></script>
		<script src="{% static 'db_static/js/bootstrap.js' %}" type="text/javascript" charset="utf-8"></script>
		<link rel="stylesheet" type="text/css" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="{% static 'db_static/css/home.css' %}">
	</head>
	<body>
		<h1 style="text-align: center;">Welcome</h1>
		<h4 style="text-align: center;">What are you wanna do</h4>
		<div id="div1">
			<ul >
				<li class="active"><a href="{% url 'db_static:home' %}"><img src="{% static 'db_static/img/home.png' %}">主页</a></li>
				<li class="active"><a href="{% url 'db_static:reg' %}"><img src="{% static 'db_static/img/reg.png' %}">注册</a></li>
				<li class="active"><a href="{% url 'db_static:login' %}"><img src="{% static 'db_static/img/login.png' %}">登录</a></li>
				<li class="active"><a href="{% url 'db_static:info' %}"><img src="{% static 'db_static/img/info.png' %}">查看当前用户信息</a></li>
				<li class="active"><a href="{% url 'db_static:changeInfo' %}"><img src="{% static 'db_static/img/changeInfo.png' %}">修改当前用户信息</a></li>
				<li class="active"><a href="{% url 'db_static:changePsw' %}"><img src="{% static 'db_static/img/changePsw.png' %}">修改当前用户密码</a></li>
				<li class="active"><a href="{% url 'db_static:users' %}"><img src="{% static 'db_static/img/users.png' %}">查看用户列表</a></li>
				<li class="active"><a href="{% url 'db_static:delete' %}"><img src="{% static 'db_static/img/delete.png' %}">删除当前用户</a></li>
			</ul>
		</div>
	</body>
</html>

test_1/db_static/templates/db_static/info_show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'db_static/css/info.css' %}">
    <script src="{% static 'db_static/js/jquery-2.1.4.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'db_static/js/bootstrap.js' %}" type="text/javascript" charset="utf-8"></script>
    <!--<link rel="stylesheet" type="text/css" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"/>-->
</head>
<body>
<div id="info_div">
    <table class="hovertable">
        <caption>{{name}}</caption>
        <tr onmouseover="this.style.backgroundColor='#ccccff';" onmouseout="this.style.backgroundColor='#d4e3e5';">
            <td>name:</td>
            <td>{{name}}</td>
        </tr>
        <tr onmouseover="this.style.backgroundColor='#ccccff';" onmouseout="this.style.backgroundColor='#d4e3e5';">
            <td>age</td>
            <td>{{age}}</td>
        </tr>
        <tr onmouseover="this.style.backgroundColor='#ccccff';" onmouseout="this.style.backgroundColor='#d4e3e5';">
            <td>gender</td>
            <td>{{gender}}</td>
        </tr>
        <tr onmouseover="this.style.backgroundColor='#ccccff';" onmouseout="this.style.backgroundColor='#d4e3e5';">
            <td>address</td>
            <td>{{address}}</td>
        </tr>
    </table>
    <a class="active" href="{% url 'db_static:home' %}"><img src="{% static 'db_static/img/home.png' %}"></a>

</div>
</body>
</html>

test_1/db_static/templates/db_static/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'db_static/css/reg.css' %}">
</head>
<body>
    <div id="reg">
        <h1>Login</h1>
        <form action="{% url 'db_static:doLogin' %}" method="post">
            <input type="text" required="required" placeholder="用户名" name="name">
            <input type="password" required="required" placeholder="密码" name="psw">
            <button class="button_1" type="submit">登录</button>
        </form>
    </div>
</body>
</html>

test_1/db_static/templates/db_static/login_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'db_static/css/reg.css' %}">
</head>
<body>
    <div id="reg">
        <h1> Fail to Login </h1>

    </div>
    <div id="time">
            <h2><span id="sp">5</span>seconds later skip to login page...</h2>
                <script>
                    onload=function () {
                        setInterval(go,1000)
                    };
                    var x=4;
                    function go() {

                        if (x>=0){
                            document.getElementById("sp").innerText=x;
                        }else {
                            location.href="{% url 'db_static:login' %}";
                        }
                        x--;
                    }
                </script>
    </div>
</body>
</html>

test_1/db_static/templates/db_static/login_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'db_static/css/reg.css' %}">
</head>
<body>
    <div id="reg">
        <h1> Login Successfully </h1>

    </div>

    <div id="time">
        <h2><span id="sp">5</span>seconds later skip to home page...</h2>
            <script>
                onload=function () {
                    setInterval(go,1000)
                };
                var x=4;
                function go() {

                    if (x>=0){
                        document.getElementById("sp").innerText=x;
                    }else {
                        location.href="{% url 'db_static:home' %}";
                    }
                    x--;
                }
            </script>
    </div>


</body>
</html>

test_1/db_static/templates/db_static/reg_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'db_static/css/reg.css' %}">
</head>
<body>
    <div id="reg">
        <h1> Fail to Register </h1>

    </div>
    <div id="time">
        <h2><span id="sp">5</span>seconds later skip to register page...</h2>
            <script>
                onload=function () {
                    setInterval(go,1000)
                };
                var x=4;
                function go() {

                    if (x>=0){
                        document.getElementById("sp").innerText=x;
                    }else {
                        location.href="{% url 'db_static:reg' %}";
                    }
                    x--;
                }
            </script>
    </div>
</body>
</html>

test_1/db_static/templates/db_static/reg_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'db_static/css/reg.css' %}">
</head>
<body>
    <div id="reg">
        <h1> Registered Successfully </h1>

    </div>
    <div id="time">
            <h2><span id="sp">5</span>seconds later skip to home page...</h2>
                <script>
                    onload=function () {
                        setInterval(go,1000)
                    };
                    var x=4;
                    function go() {

                        if (x>=0){
                            document.getElementById("sp").innerText=x;
                        }else {
                            location.href="{% url 'db_static:home' %}";
                        }
                        x--;
                    }
                </script>
    </div>
</body>
</html>